/**
 * This file is part of the Titan Flight Computer Project
 * Copyright (c) 2024 UW SARP
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 * 
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 * 
 * @file src/port/gcc_arm_stm32h745_cm7/core.h
 * @authors Aaron McBride
 * @brief Implementation of core language facilities for the gcc_arm_stm32h745_cm7 port.
 */

#ifndef SRC_PORT_GCC_ARM_STM32H745_CM7_CORE_INC
#define SRC_PORT_GCC_ARM_STM32H745_CM7_CORE_INC

#if defined(__cplusplus)
  extern "C" {
#endif

  /************************************************************************************************
   * @section 
   ************************************************************************************************/

#if defined(__cplusplus)
  } /* extern "C" */
#endif

#endif /* SRC_PORT_GCC_ARM_STM32H745_CM7_CORE_INC */