name: Build program

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  cmake-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install ARM GCC toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi

      - name: CMake configure
        run: cmake -S . -B build

      - name: Build all targets
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install ARM GCC toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi

      - name: Install clang-tidy
        run: sudo apt-get install -y clang-tidy

      - name: CMake configure
        run: cmake -S . -B build

      - name: Build compile_commands.json
        run: cmake --build build --target titan.elf

      - name: Run clang-tidy
        run: find src -name "*.c" | xargs clang-tidy -p build --quiet